nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM1Layer10H --num-rnn-layers 1 --hidden-dim 10 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM1Layer50H --num-rnn-layers 1 --hidden-dim 50 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM1Layer100H --num-rnn-layers 1 --hidden-dim 100 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM2Layer10H --num-rnn-layers 2 --hidden-dim 10 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM2Layer50H --num-rnn-layers 2 --hidden-dim 50 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM2Layer100H --num-rnn-layers 2 --hidden-dim 100 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM3Layer10H --num-rnn-layers 3 --hidden-dim 10 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM3Layer50H --num-rnn-layers 3 --hidden-dim 50 --lr 0.5 --momentum 0.5
nice -n 19 python -u train_pad.py --model LSTM --model-num LSTM3Layer100H --num-rnn-layers 3 --hidden-dim 100 --lr 0.5 --momentum 0.5
